### ISSUE TITLE
第一期选题

### ISSUE THREAD

**Issue by Hansimov** [Hansimov/sci-tech-history#1]

**Comment by veroyatnost** [comment]
### 可选的议题
#### 偏向于追热点的相关议题
1. 在没有计算机之前，我们是怎么算出工程参数的
2. 下饺子时期，船舶发展史，从小木板到航空母舰

#### 比较有趣的议题
1. 科学史上的伟大家族，以一个家族为一个议题（理论上是能够全部接上的，即，这是一个非常庞大的议题）
2. 八卦的科学史（太点，而且没什么营养，最多作为某一个分支出现）

**Comment by Hansimov** [comment]
经过讨论，决定第一期主题为：

**在计算机发明前，我们用什么计算？** 对象是计算尺。

文案由 cby 负责，mov 则开始设计logo和片头。

**Comment by veroyatnost** [comment]
# 参考文献或积累素材
## 计算尺相关的技术
[计算尺_知乎问题](https://www.zhihu.com/question/33437910)
[计算尺_回答](https://www.zhihu.com/question/34531651/answer/110690410)
[计算尺的模拟](http://www.antiquark.com/sliderule/sim/index.html)
[制作一个计算尺](http://solar.physics.montana.edu/kankel/math/csr.html)
[计算尺的纸片模型_可制作](https://www.ee.ryerson.ca/~elf/ancient-comp/sliderule.pdf)
[计算尺的模拟](https://www.sagmilling.com/tools/sliderule/)

[The Slide Rule - singingbanana (YouTube)](https://www.youtube.com/watch?v=waiprjueVpQ)
[Slide rule - Wikipedia](https://en.wikipedia.org/wiki/Slide_rule)


# 一个可选的框架
由提问“用什么计算？”引出计算尺的计算方法以及工程技术内容，后引入对数运算以及换底公式说明；其后给出几类对数的定义方式。
后续应当补充出更多的分类方式，譬如有哪些著名的计算尺，我国制造过哪些。

应当考虑配音，到时候我/CBY可以负责。

**Comment by Hansimov** [comment]
关于选题的调整建议：
计算尺只是诸多机械计算器的种类之一，如果直接以“计算机出现之前我们用什么计算”引出计算尺，是否显得太过局限？
或者直接介绍机械计算器的发展历史？

**Comment by Hansimov** [comment]
被抢先一步：[【混乱博物馆】计算机之前的计算机](https://www.bilibili.com/video/av24472833)

所以第一期是否考虑换个主题？
